from django.urls import path
from .views import (
    CategoriaListView,
    CategoriaDetailView,
    CategoriaCreateView,
    CategoriaUpdateView,
    CategoriaDeleteView,
    MarcaListView,
    MarcaCreateView,
    MarcaDetailView,
    MarcaUpdateView,
    MarcaDeleteView,
    ProveedorListView,
    ProveedorCreateView,
    ProveedorDetailView,
    ProveedorUpdateView,
    ProveedorDeleteView,
    ProductoListView,
    ProductoCreateView,
    ProductoDetailView,
    ProductoUpdateView,
    ProductoDeleteView,
    VentaListView,
    VentaCreateView,
    VentaDetailView,
    VentaUpdateView,
    VentaDeleteView,
    ClienteListView,
    ClienteCreateView,
    ClienteDetailView,
    ClienteUpdateView,
    ClienteDeleteView,
    ClienteListView,
    ClienteCreateView,
    ClienteDetailView,
    ClienteUpdateView,
    ClienteDeleteView,
    DetalleVentaListView,
    DetalleVentaCreateView,
    DetalleVentaDetailView,
    DetalleVentaUpdateView,
    DetalleVentaDeleteView,
    CompraListView,
    CompraCreateView,
    CompraDetailView,
    CompraUpdateView,
    CompraDeleteView,
    DetalleCompraListView,
    DetalleCompraCreateView,
    DetalleCompraDetailView,
    DetalleCompraUpdateView,
    DetalleCompraDeleteView,
    InventarioListView, 
    InventarioCreateView, 
    InventarioDetailView, 
    InventarioUpdateView, 
    InventarioDeleteView,
    PromocionListView, 
    PromocionCreateView, 
    PromocionDetailView, 
    PromocionUpdateView, 
    PromocionDeleteView,
    inicio,
)

urlpatterns = [
    #Pagina de Incio
     path('', inicio, name='inicio'),
    # URLs para Categoria
    path("categorias/", CategoriaListView.as_view(), name="categoria-list"),
    path("categorias/<int:pk>/", CategoriaDetailView.as_view(), name="categoria-detail"),
    path("categorias/nueva/", CategoriaCreateView.as_view(), name="categoria-create"),
    path("categorias/<int:pk>/editar/",CategoriaUpdateView.as_view(),name="categoria-update",),
    path("categorias/<int:pk>/eliminar/",CategoriaDeleteView.as_view(),name="categoria-delete",),
    #Urls para Marca
    path("marcas/", MarcaListView.as_view(), name="marca-list"),
    path('marcas/nueva/', MarcaCreateView.as_view(), name='marca-create'),
    path('marcas/<int:pk>/', MarcaDetailView.as_view(), name='marca-detail'),
    path('marcas/<int:pk>/editar/', MarcaUpdateView.as_view(), name='marca-update'),
    path('marcas/<int:pk>/eliminar/', MarcaDeleteView.as_view(), name='marca-delete'),
    #Urls para Proveedor
    path('proveedores/', ProveedorListView.as_view(), name='proveedor-list'), 
    path('proveedores/nuevo/', ProveedorCreateView.as_view(), name='proveedor-create'),
    path('proveedores/<int:pk>/', ProveedorDetailView.as_view(), name='proveedor-detail'),
    path('proveedores/<int:pk>/editar/', ProveedorUpdateView.as_view(), name='proveedor-update'),
    path('proveedores/<int:pk>/eliminar/', ProveedorDeleteView.as_view(), name='proveedor-delete'),
    #Urls para Productos
    path('productos/', ProductoListView.as_view(), name='producto-list'),
    path('productos/nuevo/', ProductoCreateView.as_view(), name='producto-create'),
    path('productos/<int:pk>/', ProductoDetailView.as_view(), name='producto-detail'),  
    path('productos/<int:pk>/editar/', ProductoUpdateView.as_view(), name='producto-update'),  
    path('productos/<int:pk>/eliminar/', ProductoDeleteView.as_view(), name='producto-delete'),
    #Urls para Cliente
    path('clientes/', ClienteListView.as_view(), name='cliente-list'),
    path('clientes/nuevo/', ClienteCreateView.as_view(), name='cliente-create'),
    path('clientes/<int:pk>/', ClienteDetailView.as_view(), name='cliente-detail'),
    path('clientes/<int:pk>/editar/', ClienteUpdateView.as_view(), name='cliente-update'),
    path('clientes/<int:pk>/eliminar/', ClienteDeleteView.as_view(), name='cliente-delete'),
    #Urls para Venta
    path('ventas/', VentaListView.as_view(), name='venta-list'), 
    path('ventas/nueva/', VentaCreateView.as_view(), name='venta-create'),
    path('ventas/<int:pk>/', VentaDetailView.as_view(), name='venta-detail'), 
    path('ventas/<int:pk>/editar/', VentaUpdateView.as_view(), name='venta-update'),
    path('ventas/<int:pk>/eliminar/', VentaDeleteView.as_view(), name='venta-delete'),
    #Urls para Detalle Venta
    path('detalleventas/', DetalleVentaListView.as_view(), name='detalleventa-list'),
    path('detalleventas/nuevo/', DetalleVentaCreateView.as_view(), name='detalleventa-create'),
    path('detalleventas/<int:pk>/', DetalleVentaDetailView.as_view(), name='detalleventa-detail'), 
    path('detalleventas/<int:pk>/editar/', DetalleVentaUpdateView.as_view(), name='detalleventa-update'), 
    path('detalleventas/<int:pk>/eliminar/', DetalleVentaDeleteView.as_view(), name='detalleventa-delete'),
    #Url para Compra
    path('compras/', CompraListView.as_view(), name='compra-list'), 
    path('compras/nueva/', CompraCreateView.as_view(), name='compra-create'), 
    path('compras/<int:pk>/', CompraDetailView.as_view(), name='compra-detail'), 
    path('compras/<int:pk>/editar/', CompraUpdateView.as_view(), name='compra-update'),
    path('compras/<int:pk>/eliminar/', CompraDeleteView.as_view(), name='compra-delete'),
    #Url para Detalle Compra
    path('detallecompra/', DetalleCompraListView.as_view(), name='detallecompra-list'),
    path('detallecompra/nueva/', DetalleCompraCreateView.as_view(), name='detallecompra-create'),
    path('detallecompra/<int:pk>/', DetalleCompraDetailView.as_view(), name='detallecompra-detail'),
    path('detallecompra/<int:pk>/editar/', DetalleCompraUpdateView.as_view(), name='detallecompra-update'),
    path('detallecompra/<int:pk>/eliminar/', DetalleCompraDeleteView.as_view(), name='detallecompra-delete'),
    #Urls para Inventario
    path('inventario/', InventarioListView.as_view(), name='inventario-list'),
    path('inventario/nuevo/', InventarioCreateView.as_view(), name='inventario-create'),
    path('inventario/<int:pk>/', InventarioDetailView.as_view(), name='inventario-detail'),
    path('inventario/<int:pk>/editar/', InventarioUpdateView.as_view(), name='inventario-update'),
    path('inventario/<int:pk>/eliminar/', InventarioDeleteView.as_view(), name='inventario-delete'),
    #Urls para Promociones
     path('promociones/', PromocionListView.as_view(), name='promocion-list'),
    path('promociones/nuevo/', PromocionCreateView.as_view(), name='promocion-create'),
    path('promociones/<int:pk>/', PromocionDetailView.as_view(), name='promocion-detail'),
    path('promociones/<int:pk>/editar/', PromocionUpdateView.as_view(), name='promocion-update'),
    path('promociones/<int:pk>/eliminar/', PromocionDeleteView.as_view(), name='promocion-delete'),

]
